### PR TITLE
Add support for snapshot versions display

### PR DESCRIPTION
**Pull request by Siphalor**
As the title states

### CODE REVIEW

**Comment by way2muchnoise** [comment]
Could you add some screenshots of what the badge would look like?

**Comment by Siphalor** [comment]
It removes the '-Snapshot' part so it just looks like before.
It only adds the supported versions.

[](https://postimg.cc/cryttS51)

I thought about leaving the '-Snapshot' part but this might get a bit too wide.

**Comment by way2muchnoise** [comment]
Cool, thx for the contribution. Should be up in a couple mins on the site.

**Comment by way2muchnoise** [comment]
Made the list of version unique in b317f12e4163c03c6cae1381f3d7f391cde63c0e, as before it was displaying it multiple times when there was both a file for the snapshot and full version.

**Comment by Siphalor** [comment]
Ah sorry, didn't test that

**Pull request merged**
