### PR TITLE
Created wiki(Does this work with PR?) and fixed index.html

### PR DESCRIPTION
**Pull request by dbarnes18**
I hope this is good?
The links and images won't work on my fork, because I put the links as if it was merged.

I don't know if wikis are carried across forks either...

I also fixed the images in index.html because you had them on `https`

Hope that it is good?

WIKI: https://github.com/dbarnes18/CurseForgeBadge/wiki

### CODE REVIEW

**Comment by way2muchnoise** [comment]
Normally you should be able to just create wiki pages on my project directly.
HTTPS links on the index page should work fine, but I do notice an issue with using project slugs instead of project IDs.

Gonna close this PR, please just try to create the wiki pages directly.

**Comment by dbarnes18** [comment]
@way2muchnoise I can't create a page on your wiki, because I am not a collaborator.

If I try to go to https://github.com/way2muchnoise/CurseForgeBadge/wiki, then it just redirects me to your README.

**Comment by way2muchnoise** [comment]
Copied over your wiki content :) Added a little link to your profile as creator

**Comment by dbarnes18** [comment]
Thanks then! Hope it is good.

**Comment by dbarnes18** [comment]
My final suggestion is issue templates so people know information to put when creating issues. I did some here, but they might not be good enough: https://github.com/dbarnes18/CurseForgeBadge/tree/master/.github/ISSUE_TEMPLATE

**Comment by way2muchnoise** [comment]
To be honest, if you want to create a badge for CF project you should be capable of writing a proper issue report. This is not a very complex environment. It is just a single web call that returns an SVG.

**Pull request closed without merging**
